require('plugins')
vim.cmd('colorscheme palenight')
require('tree-sitter')
require('vim-settings')
require('lua-line')
require('buffer-line')
require('nvim-tree-settings')
require('auto-pairs')
require('custom_keys')
require('whichkey-plugin')
require('telescope-config')
require('lsp')
require('colorizer-conf')
require('terminal-conf')
require('commenter')
